# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fgo.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QLabel,
    QLineEdit, QPushButton, QRadioButton, QSizePolicy,
    QTextBrowser, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(898, 785)
        font = QFont()
        font.setFamilies([u".AppleSystemUIFont"])
        font.setPointSize(13)
        Form.setFont(font)
        self.textBrowser_log = QTextBrowser(Form)
        self.textBrowser_log.setObjectName(u"textBrowser_log")
        self.textBrowser_log.setGeometry(QRect(10, 470, 881, 271))
        self.widget_cfg = QWidget(Form)
        self.widget_cfg.setObjectName(u"widget_cfg")
        self.widget_cfg.setGeometry(QRect(520, 10, 371, 451))
        self.pushButton_adbconnect = QPushButton(self.widget_cfg)
        self.pushButton_adbconnect.setObjectName(u"pushButton_adbconnect")
        self.pushButton_adbconnect.setGeometry(QRect(10, 0, 81, 51))
        self.pushButton_screenshot = QPushButton(self.widget_cfg)
        self.pushButton_screenshot.setObjectName(u"pushButton_screenshot")
        self.pushButton_screenshot.setGeometry(QRect(100, 0, 81, 51))
        self.pushButton_screenshot.setAutoExclusive(False)
        self.pushButton_loadcfg = QPushButton(self.widget_cfg)
        self.pushButton_loadcfg.setObjectName(u"pushButton_loadcfg")
        self.pushButton_loadcfg.setEnabled(True)
        self.pushButton_loadcfg.setGeometry(QRect(190, 0, 81, 51))
        self.pushButton_savecfg = QPushButton(self.widget_cfg)
        self.pushButton_savecfg.setObjectName(u"pushButton_savecfg")
        self.pushButton_savecfg.setEnabled(True)
        self.pushButton_savecfg.setGeometry(QRect(280, 0, 81, 51))
        self.textBrowser_cfg = QTextBrowser(self.widget_cfg)
        self.textBrowser_cfg.setObjectName(u"textBrowser_cfg")
        self.textBrowser_cfg.setGeometry(QRect(10, 60, 351, 271))
        self.textBrowser_cfg.setAutoFillBackground(False)
        self.pushButton_autobattle = QPushButton(self.widget_cfg)
        self.pushButton_autobattle.setObjectName(u"pushButton_autobattle")
        self.pushButton_autobattle.setGeometry(QRect(10, 340, 81, 101))
        font1 = QFont()
        font1.setFamilies([u"SF Mono"])
        font1.setPointSize(13)
        font1.setBold(True)
        self.pushButton_autobattle.setFont(font1)
        self.pushButton_autobattle.setStyleSheet(u"")
        self.pushButton_pypoint = QPushButton(self.widget_cfg)
        self.pushButton_pypoint.setObjectName(u"pushButton_pypoint")
        self.pushButton_pypoint.setGeometry(QRect(190, 340, 81, 51))
        self.pushButton_py_craft = QPushButton(self.widget_cfg)
        self.pushButton_py_craft.setObjectName(u"pushButton_py_craft")
        self.pushButton_py_craft.setGeometry(QRect(280, 340, 81, 51))
        self.pushButton_craftexp = QPushButton(self.widget_cfg)
        self.pushButton_craftexp.setObjectName(u"pushButton_craftexp")
        self.pushButton_craftexp.setGeometry(QRect(190, 390, 81, 51))
        self.pushButton_stop = QPushButton(self.widget_cfg)
        self.pushButton_stop.setObjectName(u"pushButton_stop")
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setGeometry(QRect(100, 340, 81, 101))
        self.pushButton_stop.setFont(font1)
        self.pushButton_stop.setStyleSheet(u"")
        self.widget_run = QWidget(Form)
        self.widget_run.setObjectName(u"widget_run")
        self.widget_run.setGeometry(QRect(10, 10, 511, 81))
        self.label = QLabel(self.widget_run)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 61, 31))
        font2 = QFont()
        font2.setFamilies([u".AppleSystemUIFont"])
        font2.setPointSize(13)
        font2.setBold(True)
        font2.setItalic(True)
        font2.setUnderline(True)
        self.label.setFont(font2)
        self.label.setStyleSheet(u"color:rgb(255, 38, 0)")
        self.comboBox_type = QComboBox(self.widget_run)
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.setObjectName(u"comboBox_type")
        self.comboBox_type.setGeometry(QRect(0, 40, 81, 32))
        self.label_4 = QLabel(self.widget_run)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 10, 61, 31))
        self.comboBox_subtype = QComboBox(self.widget_run)
        self.comboBox_subtype.setObjectName(u"comboBox_subtype")
        self.comboBox_subtype.setEnabled(False)
        self.comboBox_subtype.setGeometry(QRect(90, 40, 201, 31))
        self.label_19 = QLabel(self.widget_run)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(300, 10, 31, 31))
        self.comboBox_run_task = QComboBox(self.widget_run)
        self.comboBox_run_task.setObjectName(u"comboBox_run_task")
        self.comboBox_run_task.setGeometry(QRect(290, 40, 171, 32))
        self.label_3 = QLabel(self.widget_run)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(470, 10, 31, 31))
        self.lineEdit_run_times = QLineEdit(self.widget_run)
        self.lineEdit_run_times.setObjectName(u"lineEdit_run_times")
        self.lineEdit_run_times.setGeometry(QRect(470, 40, 31, 31))
        self.pushButton_task_refresh = QPushButton(self.widget_run)
        self.pushButton_task_refresh.setObjectName(u"pushButton_task_refresh")
        self.pushButton_task_refresh.setGeometry(QRect(400, 10, 51, 32))
        self.widget_addap = QWidget(Form)
        self.widget_addap.setObjectName(u"widget_addap")
        self.widget_addap.setGeometry(QRect(10, 90, 511, 81))
        self.widget_auto_apple = QWidget(self.widget_addap)
        self.widget_auto_apple.setObjectName(u"widget_auto_apple")
        self.widget_auto_apple.setGeometry(QRect(210, 10, 121, 31))
        self.radioButton_apple_on = QRadioButton(self.widget_auto_apple)
        self.radioButton_apple_on.setObjectName(u"radioButton_apple_on")
        self.radioButton_apple_on.setGeometry(QRect(0, 0, 41, 31))
        self.radioButton_apple_off = QRadioButton(self.widget_auto_apple)
        self.radioButton_apple_off.setObjectName(u"radioButton_apple_off")
        self.radioButton_apple_off.setEnabled(True)
        self.radioButton_apple_off.setGeometry(QRect(50, 0, 41, 31))
        self.radioButton_apple_off.setChecked(True)
        self.label_15 = QLabel(self.widget_addap)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(100, 10, 101, 31))
        self.widget_auto_stone = QWidget(self.widget_addap)
        self.widget_auto_stone.setObjectName(u"widget_auto_stone")
        self.widget_auto_stone.setGeometry(QRect(210, 40, 121, 31))
        self.radioButton_stone_on = QRadioButton(self.widget_auto_stone)
        self.radioButton_stone_on.setObjectName(u"radioButton_stone_on")
        self.radioButton_stone_on.setGeometry(QRect(0, 0, 41, 31))
        self.radioButton_stone_off = QRadioButton(self.widget_auto_stone)
        self.radioButton_stone_off.setObjectName(u"radioButton_stone_off")
        self.radioButton_stone_off.setGeometry(QRect(50, 0, 41, 31))
        self.radioButton_stone_off.setChecked(True)
        self.label_14 = QLabel(self.widget_addap)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 10, 61, 31))
        self.label_14.setFont(font2)
        self.label_14.setStyleSheet(u"color:rgb(255, 38, 0)")
        self.label_16 = QLabel(self.widget_addap)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(100, 40, 101, 31))
        self.widget_support = QWidget(Form)
        self.widget_support.setObjectName(u"widget_support")
        self.widget_support.setGeometry(QRect(10, 170, 511, 111))
        self.comboBox_refresh = QComboBox(self.widget_support)
        self.comboBox_refresh.addItem("")
        self.comboBox_refresh.addItem("")
        self.comboBox_refresh.addItem("")
        self.comboBox_refresh.setObjectName(u"comboBox_refresh")
        self.comboBox_refresh.setGeometry(QRect(420, 40, 81, 32))
        self.label_13 = QLabel(self.widget_support)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(320, 40, 101, 31))
        self.checkBox_rank_6 = QCheckBox(self.widget_support)
        self.checkBox_rank_6.setObjectName(u"checkBox_rank_6")
        self.checkBox_rank_6.setGeometry(QRect(330, 10, 41, 31))
        self.checkBox_manpo = QCheckBox(self.widget_support)
        self.checkBox_manpo.setObjectName(u"checkBox_manpo")
        self.checkBox_manpo.setEnabled(False)
        self.checkBox_manpo.setGeometry(QRect(250, 70, 51, 31))
        self.checkBox_manpo.setChecked(True)
        self.label_2 = QLabel(self.widget_support)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 61, 31))
        font3 = QFont()
        font3.setFamilies([u".AppleSystemUIFont"])
        font3.setPointSize(13)
        font3.setBold(True)
        font3.setItalic(True)
        font3.setUnderline(True)
        font3.setStrikeOut(False)
        self.label_2.setFont(font3)
        self.label_2.setStyleSheet(u"color:rgb(255, 38, 0)")
        self.checkBox_rank_4 = QCheckBox(self.widget_support)
        self.checkBox_rank_4.setObjectName(u"checkBox_rank_4")
        self.checkBox_rank_4.setGeometry(QRect(250, 10, 41, 31))
        self.checkBox_rank_0 = QCheckBox(self.widget_support)
        self.checkBox_rank_0.setObjectName(u"checkBox_rank_0")
        self.checkBox_rank_0.setGeometry(QRect(90, 10, 41, 31))
        self.comboBox_servant = QComboBox(self.widget_support)
        self.comboBox_servant.addItem("")
        self.comboBox_servant.setObjectName(u"comboBox_servant")
        self.comboBox_servant.setGeometry(QRect(50, 40, 191, 32))
        self.checkBox_rank_7 = QCheckBox(self.widget_support)
        self.checkBox_rank_7.setObjectName(u"checkBox_rank_7")
        self.checkBox_rank_7.setGeometry(QRect(370, 10, 41, 31))
        self.checkBox_rank_1 = QCheckBox(self.widget_support)
        self.checkBox_rank_1.setObjectName(u"checkBox_rank_1")
        self.checkBox_rank_1.setGeometry(QRect(130, 10, 41, 31))
        self.label_6 = QLabel(self.widget_support)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 41, 31))
        self.checkBox_rank_2 = QCheckBox(self.widget_support)
        self.checkBox_rank_2.setObjectName(u"checkBox_rank_2")
        self.checkBox_rank_2.setGeometry(QRect(170, 10, 41, 31))
        self.label_5 = QLabel(self.widget_support)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 41, 31))
        self.checkBox_rank_5 = QCheckBox(self.widget_support)
        self.checkBox_rank_5.setObjectName(u"checkBox_rank_5")
        self.checkBox_rank_5.setGeometry(QRect(290, 10, 41, 31))
        self.checkBox_rank_5.setChecked(True)
        self.label_12 = QLabel(self.widget_support)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(320, 70, 101, 31))
        self.checkBox_rank_3 = QCheckBox(self.widget_support)
        self.checkBox_rank_3.setObjectName(u"checkBox_rank_3")
        self.checkBox_rank_3.setGeometry(QRect(210, 10, 41, 31))
        self.comboBox_keepgo = QComboBox(self.widget_support)
        self.comboBox_keepgo.addItem("")
        self.comboBox_keepgo.addItem("")
        self.comboBox_keepgo.setObjectName(u"comboBox_keepgo")
        self.comboBox_keepgo.setGeometry(QRect(420, 70, 81, 32))
        self.checkBox_rank_8 = QCheckBox(self.widget_support)
        self.checkBox_rank_8.setObjectName(u"checkBox_rank_8")
        self.checkBox_rank_8.setGeometry(QRect(410, 10, 41, 31))
        self.checkBox_rank_9 = QCheckBox(self.widget_support)
        self.checkBox_rank_9.setObjectName(u"checkBox_rank_9")
        self.checkBox_rank_9.setGeometry(QRect(450, 10, 51, 31))
        self.comboBox_craft = QComboBox(self.widget_support)
        self.comboBox_craft.addItem("")
        self.comboBox_craft.setObjectName(u"comboBox_craft")
        self.comboBox_craft.setGeometry(QRect(50, 70, 191, 32))
        self.checkBox_skill_310 = QCheckBox(self.widget_support)
        self.checkBox_skill_310.setObjectName(u"checkBox_skill_310")
        self.checkBox_skill_310.setEnabled(False)
        self.checkBox_skill_310.setGeometry(QRect(250, 40, 51, 31))
        self.checkBox_skill_310.setChecked(True)
        self.widget_skill = QWidget(Form)
        self.widget_skill.setObjectName(u"widget_skill")
        self.widget_skill.setGeometry(QRect(10, 280, 511, 121))
        self.checkBox_XJBD = QCheckBox(self.widget_skill)
        self.checkBox_XJBD.setObjectName(u"checkBox_XJBD")
        self.checkBox_XJBD.setGeometry(QRect(90, 10, 61, 31))
        self.label_11 = QLabel(self.widget_skill)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 61, 31))
        self.label_11.setFont(font2)
        self.label_11.setStyleSheet(u"color:rgb(255, 38, 0)")
        self.label_11.setTextFormat(Qt.AutoText)
        self.comboBox_skill_unit = QComboBox(self.widget_skill)
        self.comboBox_skill_unit.addItem("")
        self.comboBox_skill_unit.addItem("")
        self.comboBox_skill_unit.setObjectName(u"comboBox_skill_unit")
        self.comboBox_skill_unit.setGeometry(QRect(430, 40, 81, 32))
        self.comboBox_ultimate_unit = QComboBox(self.widget_skill)
        self.comboBox_ultimate_unit.addItem("")
        self.comboBox_ultimate_unit.addItem("")
        self.comboBox_ultimate_unit.setObjectName(u"comboBox_ultimate_unit")
        self.comboBox_ultimate_unit.setGeometry(QRect(430, 80, 81, 32))
        self.label_7 = QLabel(self.widget_skill)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QRect(10, 40, 41, 31))
        self.label_9 = QLabel(self.widget_skill)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(440, 10, 41, 31))
        self.lineEdit_ultimate = QLineEdit(self.widget_skill)
        self.lineEdit_ultimate.setObjectName(u"lineEdit_ultimate")
        self.lineEdit_ultimate.setGeometry(QRect(50, 80, 381, 31))
        self.lineEdit_skill = QLineEdit(self.widget_skill)
        self.lineEdit_skill.setObjectName(u"lineEdit_skill")
        self.lineEdit_skill.setGeometry(QRect(50, 40, 381, 31))
        self.label_8 = QLabel(self.widget_skill)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 80, 41, 31))
        self.widget_priority = QWidget(Form)
        self.widget_priority.setObjectName(u"widget_priority")
        self.widget_priority.setGeometry(QRect(10, 400, 511, 61))
        self.lineEdit_color = QLineEdit(self.widget_priority)
        self.lineEdit_color.setObjectName(u"lineEdit_color")
        self.lineEdit_color.setGeometry(QRect(120, 10, 171, 31))
        self.label_18 = QLabel(self.widget_priority)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 10, 61, 31))
        self.label_18.setFont(font2)
        self.label_18.setStyleSheet(u"color:rgb(255, 38, 0)")
        self.label_18.setTextFormat(Qt.AutoText)
        self.label_10 = QLabel(self.widget_priority)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(80, 10, 41, 31))
        self.comboBox_chain_mode = QComboBox(self.widget_priority)
        self.comboBox_chain_mode.addItem("")
        self.comboBox_chain_mode.addItem("")
        self.comboBox_chain_mode.addItem("")
        self.comboBox_chain_mode.addItem("")
        self.comboBox_chain_mode.setObjectName(u"comboBox_chain_mode")
        self.comboBox_chain_mode.setGeometry(QRect(410, 10, 101, 32))
        self.label_17 = QLabel(self.widget_priority)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(370, 10, 41, 31))
        self.label_version = QLabel(Form)
        self.label_version.setObjectName(u"label_version")
        self.label_version.setGeometry(QRect(720, 760, 171, 16))
        font4 = QFont()
        font4.setFamilies([u".AppleSystemUIFont"])
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setItalic(True)
        font4.setUnderline(False)
        self.label_version.setFont(font4)
        self.label_version.setStyleSheet(u"color:rgb(4, 51, 255)")
        self.label_title = QLabel(Form)
        self.label_title.setObjectName(u"label_title")
        self.label_title.setGeometry(QRect(720, 740, 171, 31))
        font5 = QFont()
        font5.setFamilies([u".AppleSystemUIFont"])
        font5.setPointSize(20)
        font5.setBold(True)
        font5.setItalic(True)
        font5.setUnderline(False)
        self.label_title.setFont(font5)
        self.label_title.setStyleSheet(u"color:rgb(4, 51, 255)")
        self.label_log_fn = QLabel(Form)
        self.label_log_fn.setObjectName(u"label_log_fn")
        self.label_log_fn.setGeometry(QRect(10, 740, 171, 20))
        self.label_log_fn.setFont(font4)
        self.label_log_fn.setStyleSheet(u"color:rgb(4, 51, 255)")

        self.retranslateUi(Form)
        self.checkBox_XJBD.clicked.connect(Form.cstm_ckebox_skill_xjbd)
        self.comboBox_type.currentTextChanged.connect(Form.cstm_cbobox_run_param)
        self.comboBox_servant.currentTextChanged.connect(Form.cstm_cbobox_support_servant)
        self.comboBox_craft.currentTextChanged.connect(Form.cstm_cbobox_support_craft)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton_adbconnect.setText(QCoreApplication.translate("Form", u"\u8fde\u63a5", None))
        self.pushButton_screenshot.setText(QCoreApplication.translate("Form", u"\u622a\u56fe", None))
        self.pushButton_loadcfg.setText(QCoreApplication.translate("Form", u"\u52a0\u8f7d\u914d\u7f6e", None))
        self.pushButton_savecfg.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58\u914d\u7f6e", None))
        self.pushButton_autobattle.setText(QCoreApplication.translate("Form", u"\u5237\u56fe", None))
        self.pushButton_pypoint.setText(QCoreApplication.translate("Form", u"\u62bd\u53cb\u60c5", None))
        self.pushButton_py_craft.setText(QCoreApplication.translate("Form", u"\u62bd\u53cb\u60c5\n"
"\u6413\u4e38\u5b50", None))
        self.pushButton_craftexp.setText(QCoreApplication.translate("Form", u"\u6413\u4e38\u5b50", None))
        self.pushButton_stop.setText(QCoreApplication.translate("Form", u"\u505c\u6b62", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u8fd0\u884c\u53c2\u6570", None))
        self.comboBox_type.setItemText(0, QCoreApplication.translate("Form", u"\u57fa\u7840", None))
        self.comboBox_type.setItemText(1, QCoreApplication.translate("Form", u"\u6750\u6599", None))
        self.comboBox_type.setItemText(2, QCoreApplication.translate("Form", u"\u82f9\u679c", None))
        self.comboBox_type.setItemText(3, QCoreApplication.translate("Form", u"\u5723\u6676\u77f3", None))

        self.label_4.setText(QCoreApplication.translate("Form", u"\u9009\u9879", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"\u526f\u672c", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u6570\u503c", None))
        self.lineEdit_run_times.setText(QCoreApplication.translate("Form", u"1", None))
        self.pushButton_task_refresh.setText(QCoreApplication.translate("Form", u"\u5237\u65b0", None))
        self.radioButton_apple_on.setText(QCoreApplication.translate("Form", u"\u5f00", None))
        self.radioButton_apple_off.setText(QCoreApplication.translate("Form", u"\u5173", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"\u81ea\u52a8\u4f7f\u7528\u82f9\u679c", None))
        self.radioButton_stone_on.setText(QCoreApplication.translate("Form", u"\u5f00", None))
        self.radioButton_stone_off.setText(QCoreApplication.translate("Form", u"\u5173", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"\u589e\u52a0\u4f53\u529b", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"\u81ea\u52a8\u4f7f\u7528\u5723\u6676\u77f3", None))
        self.comboBox_refresh.setItemText(0, QCoreApplication.translate("Form", u"0", None))
        self.comboBox_refresh.setItemText(1, QCoreApplication.translate("Form", u"1", None))
        self.comboBox_refresh.setItemText(2, QCoreApplication.translate("Form", u"2", None))

        self.label_13.setText(QCoreApplication.translate("Form", u"\u5237\u65b0\u6b21\u6570", None))
        self.checkBox_rank_6.setText(QCoreApplication.translate("Form", u"\u6740", None))
        self.checkBox_manpo.setText(QCoreApplication.translate("Form", u"\u6ee1\u7834", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u52a9\u6218\u9009\u62e9", None))
        self.checkBox_rank_4.setText(QCoreApplication.translate("Form", u"\u9a91", None))
        self.checkBox_rank_0.setText(QCoreApplication.translate("Form", u"\u5168", None))
        self.comboBox_servant.setItemText(0, QCoreApplication.translate("Form", u"\u65e0", None))

        self.checkBox_rank_7.setText(QCoreApplication.translate("Form", u"\u72c2", None))
        self.checkBox_rank_1.setText(QCoreApplication.translate("Form", u"\u5251", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u793c\u88c5", None))
        self.checkBox_rank_2.setText(QCoreApplication.translate("Form", u"\u5f13", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u4ece\u8005", None))
        self.checkBox_rank_5.setText(QCoreApplication.translate("Form", u"\u672f", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"\u65e0\u5408\u9002\u662f\u5426\u7ee7\u7eed", None))
        self.checkBox_rank_3.setText(QCoreApplication.translate("Form", u"\u67aa", None))
        self.comboBox_keepgo.setItemText(0, QCoreApplication.translate("Form", u"\u7ee7\u7eed", None))
        self.comboBox_keepgo.setItemText(1, QCoreApplication.translate("Form", u"\u7b49\u5f85", None))

        self.checkBox_rank_8.setText(QCoreApplication.translate("Form", u"\u7279", None))
        self.checkBox_rank_9.setText(QCoreApplication.translate("Form", u"\u5408", None))
        self.comboBox_craft.setItemText(0, QCoreApplication.translate("Form", u"\u65e0", None))

        self.checkBox_skill_310.setText(QCoreApplication.translate("Form", u"310", None))
        self.checkBox_XJBD.setText(QCoreApplication.translate("Form", u"XJBD", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u6280\u80fd\u5b9d\u5177", None))
        self.comboBox_skill_unit.setItemText(0, QCoreApplication.translate("Form", u"Round", None))
        self.comboBox_skill_unit.setItemText(1, QCoreApplication.translate("Form", u"Turn", None))

        self.comboBox_ultimate_unit.setItemText(0, QCoreApplication.translate("Form", u"Round", None))
        self.comboBox_ultimate_unit.setItemText(1, QCoreApplication.translate("Form", u"Turn", None))

        self.label_7.setText(QCoreApplication.translate("Form", u"\u6280\u80fd", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u5355\u4f4d", None))
        self.lineEdit_ultimate.setText("")
        self.lineEdit_skill.setText("")
        self.label_8.setText(QCoreApplication.translate("Form", u"\u5b9d\u5177", None))
        self.lineEdit_color.setText(QCoreApplication.translate("Form", u"RBG", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"\u4f18\u5148\u7ea7", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\u8272\u5361", None))
        self.comboBox_chain_mode.setItemText(0, QCoreApplication.translate("Form", u"\u65e0", None))
        self.comboBox_chain_mode.setItemText(1, QCoreApplication.translate("Form", u"\u81ea\u52a8", None))
        self.comboBox_chain_mode.setItemText(2, QCoreApplication.translate("Form", u"\u989d\u5916\u653b\u51fb", None))
        self.comboBox_chain_mode.setItemText(3, QCoreApplication.translate("Form", u"\u8272\u5361\u8fde\u643a", None))

        self.label_17.setText(QCoreApplication.translate("Form", u"\u8fde\u643a", None))
        self.label_version.setText(QCoreApplication.translate("Form", u"v2022.XX.XX", None))
        self.label_title.setText(QCoreApplication.translate("Form", u"FGO-AUTO-RUN", None))
        self.label_log_fn.setText(QCoreApplication.translate("Form", u"???", None))
    # retranslateUi

